import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import {
  refreshCityScopedMapArtifacts,
  syncCityScopedMapControllers,
} from '../../../../open-world-platform/src/runtime/ui/city-scoped-map-controllers.js';

function fixtureController() {
  return {
    attachedMaps: [],
    detachCalls: 0,
    attachMap(map) { this.attachedMaps.push(map); },
    detachMap() { this.detachCalls += 1; },
  };
}

test('only attaches world controllers while their own city is active', () => {
  const controllers = [fixtureController(), fixtureController(), fixtureController()];
  const ownedMap = { id: 'owned-map' };
  const foreignMap = { id: 'foreign-map' };

  assert.equal(syncCityScopedMapControllers({
    map: ownedMap,
    cityCode: 'NEC_CP00_RP00',
    cityCodes: ['NEC_CP00_RP00'],
    controllers,
  }), true);
  assert.deepEqual(controllers.map((controller) => controller.attachedMaps), [
    [ownedMap], [ownedMap], [ownedMap],
  ]);

  assert.equal(syncCityScopedMapControllers({
    map: foreignMap,
    cityCode: 'KCW',
    cityCodes: ['NEC_CP00_RP00'],
    controllers,
  }), false);
  assert.deepEqual(controllers.map((controller) => controller.attachedMaps), [
    [ownedMap], [ownedMap], [ownedMap],
  ], 'foreign maps must not acquire controllers from another Open World mod');
  assert.deepEqual(controllers.map((controller) => controller.detachCalls), [1, 1, 1]);
  assert.equal(
    globalThis.__openWorldCityScopedMapControllersVersion,
    'city-scoped-map-controllers-v3',
  );
});

test('guards MapLibre layer moves before attaching an owned style controller', () => {
  const calls = [];
  const map = {
    getLayer: (id) => id === 'signal-points' ? { id } : undefined,
    moveLayer(id, beforeId) {
      calls.push([id, beforeId]);
      throw new Error(`Cannot move layer "${id}" before non-existing layer "${beforeId}".`);
    },
  };
  const controller = {
    attachMap(attachedMap) {
      attachedMap.moveLayer('signal-points', 'signal-points-under');
    },
  };

  assert.doesNotThrow(() => syncCityScopedMapControllers({
    map,
    cityCode: 'NEC_CP00_RP00',
    cityCodes: ['NEC_CP00_RP00'],
    controllers: [controller],
  }));
  assert.deepEqual(calls, [], 'controller attachment must not reach an impossible native move');
});

test('refreshes owned map artifacts once after a transition style settles', () => {
  const calls = [];
  const controller = { refresh: () => calls.push('refresh') };

  assert.deepEqual(refreshCityScopedMapArtifacts({
    map: { isStyleLoaded: () => true },
    controller,
  }), { status: 'refreshed' });
  assert.deepEqual(calls, ['refresh']);
});

test('defers the final map artifact refresh until an unsettled style becomes idle', () => {
  const calls = [];
  let idle;
  const controller = { refresh: () => calls.push('refresh') };
  const map = {
    isStyleLoaded: () => false,
    once(event, callback) {
      assert.equal(event, 'idle');
      idle = callback;
    },
  };

  assert.deepEqual(refreshCityScopedMapArtifacts({ map, controller }), { status: 'deferred-until-idle' });
  assert.deepEqual(calls, []);
  idle();
  assert.deepEqual(calls, ['refresh']);
});

test('every runnable Open World consumer scopes its map controllers by city', () => {
  const platformEntry = new URL('../../../../open-world-platform/src/runtime/start-open-world.js', import.meta.url);
  assert.match(readFileSync(platformEntry, 'utf8'), /syncCityScopedMapControllers\(\{/);

  const handwrittenConsumerEntries = [
    new URL('../../../nec-corridor/mod/src/game-entry.js', import.meta.url),
    new URL('../../../ny-state/mod/src/game-entry.js', import.meta.url),
    new URL('../../../tokyo-kanagawa/mod/src/game-entry.js', import.meta.url),
  ];
  for (const entry of handwrittenConsumerEntries) {
    assert.equal(existsSync(entry), false, `${entry.pathname} must be generated by the central builder`);
  }
});

test('a removed map or failed refresh cannot report a successful refresh', () => {
  let refreshed = false;
  assert.deepEqual(refreshCityScopedMapArtifacts({ map: { _removed: true },
    controller: { refresh() { refreshed = true; } } }), { status: 'map-removed' });
  assert.equal(refreshed, false);
  assert.deepEqual(refreshCityScopedMapArtifacts({ map: {},
    controller: { refresh() { throw new Error('style unavailable'); } } }),
  { status: 'failed', error: 'style unavailable' });
});
