import { spawnSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';

// The checked-in embedded bytes are used by both browser and Node bundles.
// --embed-only reproduces the JS module without requiring a compiler.
if (!process.argv.includes('--embed-only')) {
  const compiler = process.env.WASM_CLANG;
  if (!compiler) throw new Error('Set WASM_CLANG to the WASI SDK clang executable.');
  const flags = ['--target=wasm32-unknown-unknown', '-O3', '-ffp-contract=off', '-fno-exceptions', '-fno-rtti', '-fno-builtin', '-nostdlib',
    '-DPARTITION_EXPERIMENT', '-Wl,--no-entry', '-Wl,--export=search', '-Wl,--export=label_size', '-Wl,--export=heap_entry_size',
    '-Wl,--export=set_partition_bounds', '-Wl,--export=partition_pruned', '-Wl,--export=__heap_base',
    '-Wl,--initial-memory=131072', '-Wl,--max-memory=268435456',
    path.join(import.meta.dirname, 'transit-search.cpp'), '-o', path.join(import.meta.dirname, 'transit-search.wasm')];
  const result = spawnSync(compiler, flags, { stdio: 'inherit' });
  if (result.status !== 0) process.exit(result.status ?? 1);
}
const bytes = await readFile(path.join(import.meta.dirname, 'transit-search.wasm'));
const sha256 = createHash('sha256').update(bytes).digest('hex');
await writeFile(path.join(import.meta.dirname, 'kernel-bytes.js'),
  `// Generated by build.mjs. Do not edit. No fetch or platform-specific imports.\n`
  + `export const TRANSIT_SEARCH_WASM_SHA256 = '${sha256}';\n`
  + `const encoded = '${bytes.toString('base64')}';\n`
  + `export function transitSearchBytes() {\n`
  + `  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';\n`
  + `  const length = encoded.length * 3 / 4 - (encoded.endsWith('==') ? 2 : encoded.endsWith('=') ? 1 : 0);\n`
  + `  const result = new Uint8Array(length);\n`
  + `  let value = 0, bits = 0, index = 0;\n`
  + `  for (const character of encoded) {\n`
  + `    if (character === '=') break;\n`
  + `    value = (value << 6) | alphabet.indexOf(character); bits += 6;\n`
  + `    if (bits >= 8) { bits -= 8; result[index++] = (value >>> bits) & 255; }\n`
  + `  }\n`
  + `  return result;\n`
  + `}\n`);
console.log(JSON.stringify({ bytes: bytes.length, sha256 }));
